openapi: 3.0.0
info:
  title: phasing
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    PhasingResult:
      title: PhasingResult
      type: object
      properties:
        id:
          type: string
        date:
          type: string
    PhasingResultValueConsumer:
      title: PhasingResultValueConsumer
      type: object
      properties:
        value:
          type: string
    PhasingResultValueLine:
      title: PhasingResultValueLine
      type: object
      properties:
        id:
          type: string
    PhasingResultConsumer:
      title: PhasingResultConsumer
      type: object
      properties:
        id:
          type: string
    PhasingResultLine:
      title: PhasingResultLine
      allOf:
        - $ref: '#/components/schemas/PhasingResult'
        - type: object
          properties:
            resultValue:
              $ref: '#/components/schemas/PhasingResultValueLine'
