openapi: 3.0.0
info:
  title: SGA.v.1-draft
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/phasing/result/line/{id}':
    get:
      summary: Результат определения фаз потребителей линии
      tags:
        - Phasing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    $ref: '#/components/schemas/PhasingResult'
                required:
                  - response
      operationId: get-phasing-result-line
      description: Метод возвращает результат определения фаз потребителей линии
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID линии
  '/phasing/result/consumer/{id}':
    get:
      summary: Результат определения фаз потребителя
      tags:
        - Phasing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    $ref: '#/components/schemas/PhasingResult'
                required:
                  - response
      operationId: get-phasing-result-consumer
      description: Метод возвращает результат определения фаз потребителя
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID потребителя
components:
  schemas:
    ValueUnit:
      title: Value
      type: object
      properties:
        unit:
          type: string
          description: Единица измерения
        value:
          type: string
          description: Значение
      description: Значение и единица измерения
    PhasingResultLine:
      title: PhasingResultLine
      type: object
      description: Объект результата определения фаз потребителей линии
      properties:
        line:
          type: object
          description: Линия
          properties:
            mRID:
              type: string
              description: ID Линии
        phasingResultEnergyConsumers:
          type: array
          description: Результат определения фаз потребителей линии
          items:
            $ref: '#/components/schemas/PhasingResultEnergyConsumer'
    PhasingResultEnergyConsumer:
      title: PhasingResultEnergyConsumer
      type: object
      description: Объект результата определения фаз потребителя
      properties:
        energyConsumer:
          type: object
          description: Потребитель
          required:
            - mRID
          properties:
            mRID:
              type: string
              description: ID потребителя
        phasingResult:
          type: object
          description: Результат определения расстановки фаз потребителя
          required:
            - A
            - B
            - C
          properties:
            A:
              type: string
              description: 'Соответствие фазы A входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
            B:
              type: string
              description: 'Соответствие фазы B входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
            C:
              type: string
              description: 'Соответствие фазы C входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
        metrics:
          type: object
          description: Дополнительные показатели фазировки
          required:
            - loadBalance
          properties:
            loadBalance:
              type: object
              description: Доля нагрузки по фазам
              required:
                - A
                - B
                - C
              properties:
                A:
                  type: array
                  description: Доля нагрузки для фазы A
                  items:
                    $ref: '#/components/schemas/ValueUnit'
                B:
                  type: array
                  description: Доля нагрузки для фазы B
                  items:
                    $ref: '#/components/schemas/ValueUnit'
                C:
                  type: array
                  description: Доля нагрузки для фазы C
                  items:
                    $ref: '#/components/schemas/ValueUnit'
      required:
        - energyConsumer
        - phasingResult
        - metrics
    PhasingResult:
      title: PhasingResult
      type: object
      description: Объект результат опеределения фаз
      properties:
        phasingResult:
          oneOf:
            - $ref: '#/components/schemas/PhasingResultLine'
            - $ref: '#/components/schemas/PhasingResultEnergyConsumer'
          description: Результат определения фаз
        id:
          type: string
          description: ID результата
        date:
          type: string
          description: 'Дата и время, когда результат был получен'
          format: date-time
      required:
        - phasingResult
        - id
        - date
