openapi: 3.0.0
info:
  title: SGA
  version: '1.0'
  description: API for Smart grid analyzer
servers:
  - url: 'http://localhost:3000'
paths:
  /grid/line/getACLineSegmentPowerLosses:
    get:
      summary: Your GET endpoint
      tags:
        - Line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      ACLineSegment:
                        type: object
                        properties:
                          mRID:
                            type: string
                          powerLosses:
                            type: object
                            properties:
                              phases:
                                type: object
                                properties:
                                  A:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  B:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  C:
                                    $ref: '#/components/schemas/powerLossesValue'
      operationId: get-grid-line
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID сегмента линии
    parameters: []
  /grid/line/getLinePowerLosses:
    get:
      responses:
        - content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      line:
                        type: object
                        properties:
                          mRID:
                            type: string
                          powerLosses:
                            type: object
                            properties:
                              total:
                                $ref: '#/components/schemas/powerLossesValue'
                              phases:
                                type: object
                                properties:
                                  A:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  B:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  C:
                                    $ref: '#/components/schemas/powerLossesValue'
          description: Потери энергии для указанной Линии.
        - description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID Линии
          required: true
      tags:
        - Line
      summary: ''
      description: Потери энергии в линии.
      operationId: LinePowerLosses
    parameters: []
  /grid/consumer/getEnergyConsumerPowerLosses:
    get:
      summary: getEnergyConsumerPowerLosses
      responses: {}
      operationId: get-grid-energy-consumer-getEnergyConsumerPowerLosses
      description: Потери энергии на абонентском участке (отпайке)
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID потребителя
      tags:
        - EnergyConsumer
    parameters: []
  /grid/consumer/getEnergyConsumerSubstationPowerLosses:
    get:
      summary: getEnergyConsumerSubstationPowerLosses
      tags:
        - EnergyConsumer
      responses: {}
      operationId: get-grid-consumer-getEnergyConsumerSubstationPowerLosses
      parameters:
        - schema:
            type: string
          in: query
          name: mRIDEnergyConsumer
          description: ID потребителя
        - schema:
            type: string
          in: query
          name: mRIDSubstation
          description: ID Трансформаторной подстанции
      description: Потери энергии от ТП до Абонента
  '/grid/substation/getSubstationPowerLosses ':
    get:
      summary: Your GET endpoint
      tags:
        - Substation
      responses: {}
      operationId: get-grid-substation-get
      description: Потери энергии в ТП (силовой трансформатор и шинопровод)
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID Трансформаторной подстанции
    parameters: []
  /grid/substation/getSubstaionBuswayPowerLosses:
    get:
      summary: Your GET endpoint
      tags:
        - Substation
      responses: {}
      operationId: get-grid-substation-getSubstaionBuswayPowerLosses
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID ТП
      description: Потери энергии в шинопроводе
  /grid/substation/getSubstaionPowerTransformerPowerLosses:
    get:
      summary: Your GET endpoint
      tags:
        - Substation
      responses: {}
      operationId: get-grid-substation
      description: Потери энергии в силовом трансформаторе
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID ТП
    parameters: []
  /grid/substation/getSubstaionEnergyOrigination:
    get:
      summary: getSubstaionEnergyOrigination
      operationId: get-grid-substation-getSubstaionEnergyOrigination
      responses:
        '200':
          description: OK
      tags:
        - Substation
      description: Отданная энергия (для каждой фазы)
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: ID ТП
  /phasing/startEnergyConsumerPhasing:
    post:
      summary: ''
      operationId: post-phasing-startEnergyConsumerPhasing
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/phasing_worker'
      description: Запустить сервис определения фаз для потребителей
      tags:
        - Phasing
  /phasing/result:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phasing_result'
      operationId: get-phasing-result
      description: Получить результат расчета
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: ID результата расчета
  /phasing/result/list:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/phasing_result'
              examples:
                example-1: {}
      operationId: get-phasing-result
      description: ' Получить список всех результатов расчета соответствия фаз потребятелям'
      parameters:
        - schema:
            type: string
            format: date-time
          in: query
          name: date
          description: Получить список все результатов для указанной даты
    parameters: []
  /phasing/worker/list:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: object
                      properties:
                        worker:
                          $ref: '#/components/schemas/phasing_worker'
      operationId: get-phasing-worker-list
      description: Список всех процессов созданных для фазировки для всей сети
  '/phasing/worker/metrics/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      metrics:
                        $ref: '#/components/schemas/phasing_worker_metrics'
                      workerId:
                        type: string
                      line:
                        type: object
                        properties:
                          mRID:
                            type: string
      operationId: get-phasing-statistic
      description: Показатели (метрика) работы процесса фазировки.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Worker ID
  /phasing/stopEnergyConsumerPhasing:
    post:
      summary: ''
      operationId: post-phasing-stopEnergyConsumerPhasing
      responses:
        '202':
          description: Accepted
      description: Остановить службу определения фаз абонентов
      parameters:
        - schema:
            type: string
          in: query
          name: reason
          description: Описание причины остановки (отмены) работоющего процесса
components:
  schemas:
    powerLossesValue:
      title: powerLossesValue
      type: array
      items:
        type: object
        properties:
          value:
            type: number
          unit:
            type: string
    phasing_result:
      title: phasing_result
      type: object
      description: Результат определения фаз для потребителя
      properties:
        id:
          type: string
          description: ID result
        date:
          type: string
          description: 'Дата, когда результат фазировки был расчитан'
          format: date-time
        line:
          type: object
          required:
            - mRID
            - energy_consumer_phasing
          properties:
            mRID:
              type: string
              description: ID Линии
            energy_consumer_phasing:
              type: array
              description: Растановка входов потребителей линии в соответствии фазам линии
              items:
                type: object
                properties:
                  mRID:
                    type: string
                    description: ID потребителя для которого определены фазы
                  phasing:
                    type: object
                    description: 'Растановка L1, L2, L3 потребителя по фазам'
                    required:
                      - A
                      - B
                      - C
                    properties:
                      A:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                      B:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                      C:
                        type: string
                        enum:
                          - L1
                          - L2
                          - L3
                required:
                  - mRID
                  - phasing
      required:
        - id
        - date
        - line
    phasing_worker_metrics:
      title: phasing_worker_metrics
      type: object
      description: |
        Метрика, показатели работы процесса.
      properties:
        energyConsumer:
          type: object
          properties:
            phase_sum:
              type: object
              description: Суммы потерь электроэнергии по фазно для всех потребителей
              properties:
                A:
                  type: string
                B:
                  type: string
                C:
                  type: string
        line:
          type: object
          properties:
            phase_sum:
              type: object
              description: Суммы потерь электроэнергии по фазно для Линии
              properties:
                A:
                  type: string
                B:
                  type: string
                C:
                  type: string
            mRID:
              type: string
    phasing_worker:
      title: phasing_worker
      type: object
      x-tags:
        - Phasing
      properties:
        id:
          type: string
        start_time:
          type: string
          format: date-time
          description: Время старта процесса
        stop_time:
          type: string
          format: date-time
          description: ' Время завершения расчета для статуса Finished и время отмены для статуса Cancelled'
        status:
          type: string
          enum:
            - running
            - cancelled
            - finished
          description: 'Статус процесса: Running, Finished, Cancelled'
        сancel_resone:
          type: string
          description: 'Причина отмены, если процесс расчета фаз был отменен (статус cancelled).'
        metrics:
          $ref: '#/components/schemas/phasing_worker_metrics'
      required:
        - id
        - status
