openapi: 3.0.0
info:
  title: SGA
  version: '1.0'
  description: API for Smart grid analyzer
servers:
  - url: 'http://localhost:3000'
paths:
  /grid/line/getACLineSegmentPowerLosses:
    get:
      summary: Your GET endpoint
      tags:
        - Line
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      line:
                        type: object
                        properties:
                          mRID:
                            type: string
                          powerLosses:
                            type: object
                            properties:
                              total:
                                $ref: '#/components/schemas/powerLossesValue'
                              phases:
                                type: object
                                properties:
                                  A:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  B:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  C:
                                    $ref: '#/components/schemas/powerLossesValue'
                              '':
                                type: string
      operationId: get-grid-line
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: Line ID
    parameters: []
  /grid/line/getLinePowerLosses:
    get:
      responses:
        - content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    type: object
                    properties:
                      line:
                        type: object
                        properties:
                          mRID:
                            type: string
                          powerLosses:
                            type: object
                            properties:
                              total:
                                $ref: '#/components/schemas/powerLossesValue'
                              phases:
                                type: object
                                properties:
                                  A:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  B:
                                    $ref: '#/components/schemas/powerLossesValue'
                                  C:
                                    $ref: '#/components/schemas/powerLossesValue'
      parameters:
        - schema:
            type: string
          in: query
          name: mRID
          description: Line ID
      tags:
        - Line
      summary: ''
    parameters: []
components:
  schemas:
    powerLossesValue:
      title: powerLossesValue
      type: array
      items:
        type: object
        properties:
          value:
            type: number
          unit:
            type: string
