openapi: 3.0.0
info:
  title: SGA.v.1-draft
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/phasing/result/line/{id}':
    get:
      summary: Результат определения фаз потребителей линии
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: object
                  response:
                    $ref: '#/components/schemas/linePhasingResult'
                required:
                  - response
      operationId: get-phasing-result-line
      description: Метод возвращает результат определения фаз потребителей линии
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID линии
components:
  schemas:
    valueUnit:
      title: ValueUnit
      type: object
      properties:
        unit:
          type: string
          description: Единица измерения
        value:
          type: string
          description: Значение
      description: Значение и в чем оно измеряется
    phasingResult:
      title: PhasingResult
      type: object
      properties:
        id:
          type: string
          description: ID результата
        date:
          type: string
          format: date-time
          description: 'Дата и время, когда результат фазировки был получен'
        line:
          type: object
          properties:
            mRID:
              type: string
              description: ID объекта линии
          required:
            - mRID
          description: 'Линия, для которой выполнена фазировка'
      required:
        - id
        - date
        - line
      x-tags:
        - Phasing
        - Phasing result
      description: Объект результата фазировки
    phasingResultLine:
      title: PhasingResultLine
      type: object
      properties:
        line:
          type: object
          description: Линия
          properties:
            mRID:
              type: string
              description: ID Линии
        comsumerPhasingResults:
          type: array
          description: Результат определения фаз потребителей линии
          items:
            $ref: '#/components/schemas/energyConsumerPhasingResult'
      description: Резальтат определения фаз потребителей линии
    energyConsumerPhasingResult:
      title: energyConsumerPhasingResult
      type: object
      properties:
        energyConsumer:
          type: object
          description: Потребитель
          properties:
            mRID:
              type: string
              description: ID потребителя
        phasingResult:
          type: object
          description: Результат определения расстановки фаз потребителя
          properties:
            A:
              type: string
              description: 'Соответствие фазы A входу (L1, L2, L3) потребителя'
            B:
              type: string
              description: 'Соответствие фазы B входу (L1, L2, L3) потребителя'
            C:
              type: string
              description: 'Соответствие фазы C входу (L1, L2, L3) потребителя'
        metrics:
          type: object
          description: Дополнительные показатели фазировки
          properties:
            loadBalance:
              type: object
              description: Доля нагрузки по фазам
              properties:
                A:
                  type: array
                  description: Доля нагрузки для фазы A
                  items:
                    $ref: './SGA.v1.yaml#/components/schemas/valueUnit'
                B:
                  type: array
                  description: Доля нагрузки для фазы B
                  items:
                    $ref: './SGA.v1.yaml#/components/schemas/valueUnit'
                C:
                  type: array
                  description: Доля нагрузки для фазы C
                  items:
                    $ref: './SGA.v1.yaml#/components/schemas/valueUnit'
      description: Результат определения фаз потеребителя
    PhasingResultConsumer:
      title: PhasingResultConsumer
      type: object
      properties:
        mRID:
          type: string
        phases:
          type: object
          properties:
            A:
              type: string
            B:
              type: string
            C:
              type: string
    phasingResultEnergyConsumer:
      title: energyConsumerPhasingResult
      type: object
      description: Результа определения фаз потребителя
      properties:
        energyConsumer:
          type: object
          required:
            - mRID
          description: Потребитель
          properties:
            mRID:
              type: string
              description: ID потребителя
        phasingResult:
          type: object
          description: Результат определения расстановки фаз потребителя
          required:
            - A
            - B
            - C
          properties:
            A:
              type: string
              description: 'Соответствие фазы A входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
            B:
              type: string
              description: 'Соответствие фазы B входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
            C:
              type: string
              description: 'Соответствие фазы C входу (L1, L2, L3) потребителя'
              enum:
                - L1
                - L2
                - L3
        metrics:
          type: object
          description: Дополнительные показатели фазировки
          required:
            - loadBalance
          properties:
            loadBalance:
              type: object
              description: Доля нагрузки по фазам
              required:
                - A
                - B
                - C
              properties:
                A:
                  type: array
                  description: Доля нагрузки для фазы A
                  items:
                    $ref: '#/components/schemas/valueUnit'
                B:
                  type: array
                  description: Доля нагрузки для фазы B
                  items:
                    $ref: '#/components/schemas/valueUnit'
                C:
                  type: array
                  description: Доля нагрузки для фазы C
                  items:
                    $ref: '#/components/schemas/valueUnit'
      required:
        - energyConsumer
        - phasingResult
        - metrics
