openapi: 3.0.0
info:
  title: SmartGrid
  version: 1.0.0
  description: API for GA (Grid Analyzer) system
servers:
  - url: 'http://localhost:3000'
paths:
  /grid/create:
    post:
      summary: create
      tags:
        - Grid
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: grid-create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                header:
                  type: object
                  properties:
                    file_id:
                      type: string
                      description: ID for source file
                payload:
                  type: object
                  description: Grid layout in CIM model.
                  properties:
                    geographicalRegion:
                      $ref: '#/components/schemas/geographicalRegion'
              required:
                - header
                - payload
            examples:
              example-1: {}
        description: Electric Grid layout (topology).
      description: Load new grid popology.
components:
  schemas:
    geographicalRegion:
      title: geographicalRegion
      type: object
      properties:
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - mRID
        - name
        - aliasName
      description: Root element for grid layout
    tower:
      title: tower
      type: object
      description: Опора.
      properties:
        mRID:
          type: string
          description: ID
        name:
          type: string
          description: Заводское наименование
        aliasName:
          type: string
          description: Диспетчерское наименование
        description:
          type: string
          description: Описание
      required:
        - mRID
        - name
        - aliasName
    line:
      title: line
      type: object
      description: Линия отходящая от ТП.
      properties:
        ACLineSegment:
          type: object
          description: Участок линии
        energyConsumer:
          type: object
          description: Конечный потребитель
        tower:
          type: object
          description: Опора
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - ACLineSegment
        - energyConsumer
        - tower
    substation:
      title: substation
      type: object
      properties:
        mRID:
          type: string
          description: ID
        name:
          type: string
          description: Заводское наименование
        aliasName:
          type: string
          description: Диспетчерское наименование
        description:
          type: string
          description: Описание
      description: Трансформаторная подстанция (ТП)
    ACLineSegment:
      title: ACLineSegment
      type: object
      description: Конечный потребитель.
      properties:
        mRID:
          type: string
          description: ID
        name:
          type: string
          description: Заводское наименование
        aliasName:
          type: string
          description: Диспетчерское наименование
        description:
          type: string
          description: Описание
      required:
        - mRID
        - name
        - aliasName
    energyConsumer:
      title: energyConsumer
      type: object
      x-examples:
        Energy Consumer:
          mRID: 93147fc9-5fab-282f-7371-338ec4891a85
          name: МИР С-04
          aliasName: ул. Обдорская 40
          description: ''
          baseVoltage:
            nominalVoltage:
              value: 0.4
              unit: v
          location:
            mRID: '1'
            name: string
            aliasName: string
            description: string
            positionPoint:
              xPosition: '66.68189674348'
              yPosition: '66.52272427729'
            coordinateSystem:
              crsUrn: string
          terminal:
            - phases: none
              connectivityNode:
                mRID: 00000000-0000-0000-0000-000000000021
      properties:
        baseVoltage:
          type: object
          properties:
            '':
              type: string
        location:
          type: object
        terminal:
          type: object
        asset:
          type: object
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - baseVoltage
        - location
        - aliasName
        - name
        - mRID
    location:
      title: location
      type: object
      properties:
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
        coordinateSystem:
          type: object
        positionPoint:
          type: object
      required:
        - aliasName
        - name
        - mRID
    coordinateSystem:
      title: coordinateSystem
      type: object
      properties:
        crsUrn:
          type: string
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - aliasName
        - name
        - mRID
      description: ''
    positionPoint:
      title: positionPoint
      type: object
      properties:
        xPosition:
          type: string
        yPosition:
          type: string
        zPosition:
          type: string
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - mRID
        - name
        - aliasName
        - xPosition
        - yPosition
    baseVoltage:
      title: baseVoltage
      type: object
      description: Базовое напряжение
      properties:
        mRID:
          type: string
          description: ID
        name:
          type: string
          description: Заводское наименование
        aliasName:
          type: string
          description: Диспетчерское наименование
        description:
          type: string
          description: Описание
        nominalVoltage:
          type: object
          required:
            - value
            - unit
          properties:
            value:
              type: number
            unit:
              $ref: '#/components/schemas/unitSymbol'
      required:
        - mRID
        - name
        - aliasName
        - nominalVoltage
    subGeographicalRegion:
      title: subGeographicalRegion
      type: object
      description: ''
      properties:
        line:
          $ref: '#/components/schemas/line'
        substation:
          $ref: '#/components/schemas/substation'
        description:
          type: string
          description: Описание
        aliasName:
          type: string
          description: Диспетчерское наименование
        name:
          type: string
          description: Заводское наименование
        mRID:
          type: string
          description: ID
      required:
        - line
        - substation
    unitSymbol:
      type: string
      title: UnitSymbol
      enum:
        - none
        - v
      description: Еденицы измерения
